UnitedPigeonAirlines.WebUI/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UnitedPigeonAirlines.Domain.Abstract;
using UnitedPigeonAirlines.WebUI.Models;
using UnitedPigeonAirlines.EF.Repositories;
using UnitedPigeonAirlines.Data.Entities.OrderAggregate;
using UnitedPigeonAirlines.Data.Entities.CartAggregate;
using UnitedPigeonAirlines.Data.Entities.PigeonAggregate;
using UnitedPigeonAirlines.Data.Repositories;


namespace UnitedPigeonAirlines.WebUI.Controllers
{
    public class CartController : Controller
    {
        private IPigeonRepository repository;
        private IOrderRepository orderRepository;
        private IOrderProcessor orderProcessor;
        private IFactoryCaclulation priceCalcFactory;
        private IConfiguration configuration;
        


        public CartController(IPigeonRepository repo,IOrderRepository orepo, IOrderProcessor processor, IFactoryCaclulation priceCalculation, IConfiguration config)
        {
            repository = repo;
            orderRepository = orepo;
            orderProcessor = processor;
            priceCalcFactory = priceCalculation;
            configuration = config;
        }
        public ViewResult Checkout()
        {
            return View(new ShippingDetails());
        }

            public ViewResult Index(Cart cart, string returnUrl)
        {

            CartIndexViewModel indexViewModel = new CartIndexViewModel();
            indexViewModel.Cart = cart;
            indexViewModel.ReturnUrl = returnUrl;
            indexViewModel.PigeonsInCart = cart.Lines.Select(x => new PigeonInCartDTO(x, repository.GetPigeon(x.PigeonId))).ToList();
            foreach(var pig in indexViewModel.PigeonsInCart)
            {
                pig.Price = priceCalcFactory.Create(configuration.ChosenStrategyName).CalculatePrice(cart, cart.Lines.Find(x => x.PigeonId == pig.Pigeon.PigeonId));
                
            }
            return View(indexViewModel);
        }

        public RedirectToRouteResult AddToCart(Cart cart, int PigeonId, string returnUrl)
        {
            Pigeon Pigeon = repository.GetAllPigeons()
                .FirstOrDefault(g => g.PigeonId == PigeonId);

            if (Pigeon != null)
            {
                cart.AddItem(Pigeon, 1);
            }
            
            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToRouteResult RemoveFromCart(Cart cart, int PigeonId, string returnUrl)
        {
            Pigeon Pigeon = repository.GetAllPigeons()
                .FirstOrDefault(g => g.PigeonId == PigeonId);

            if (Pigeon != null)
            {
                cart.RemoveLine(Pigeon);
            }
            return RedirectToAction("Index", new { returnUrl });
        }
        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }
        [HttpPost]
        public ViewResult Checkout( Cart cart, ShippingDetails shippingDetails)
        {
            CartIndexViewModel indexViewModel = new CartIndexViewModel();
            decimal Subtotal = 0;
            indexViewModel.PigeonsInCart = cart.Lines.Select(x => new PigeonInCartDTO(x, repository.GetPigeon(x.PigeonId))).ToList();
            foreach (var pig in indexViewModel.PigeonsInCart)
            {
                pig.Price = priceCalcFactory.Create(configuration.ChosenStrategyName).CalculatePrice(cart, cart.Lines.Find(x => x.PigeonId == pig.Pigeon.PigeonId));
                Subtotal += pig.Price;
            }
            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, your cart is empty!");
            }

            if (ModelState.IsValid)
            {
                Order order = new Order();
                cart.FillOrder(order);
                order.City = shippingDetails.City;
                order.Country = shippingDetails.Country;
                order.GiftWrap = shippingDetails.GiftWrap;
                order.Line1 = shippingDetails.Line1;
                order.Line2 = shippingDetails.Line2;
                order.Line3 = shippingDetails.Line3;
                order.Name = shippingDetails.Name;
                order.SummaryPrice = Subtotal;
                orderRepository.SaveOrder(order);
                orderProcessor.ProcessOrder(order);
                cart.Clear();
                return View("Completed");
            }
            else
            {
                return View(shippingDetails);
            }
        }
    }
}

UnitedPigeonAirlines.WebUI/Controllers/NavController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UnitedPigeonAirlines.Data.Repositories;
using UnitedPigeonAirlines.EF.Repositories;

namespace UnitedPigeonAirlines.WebUI.Controllers
{
    public class NavController : Controller
    {
        private IPigeonRepository repository;

        public NavController(IPigeonRepository repo)
        {
            repository = repo;
        }

        public PartialViewResult Menu()
        {
            IEnumerable<string> categories = repository.GetAllPigeons()
                .Select(pigeon => pigeon.Category)
                .Distinct()
                .OrderBy(x => x);
            return PartialView(categories);
        }
    }
}

UnitedPigeonAirlines.WebUI/Controllers/PigeonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UnitedPigeonAirlines.EF.Repositories;
using UnitedPigeonAirlines.WebUI.Models;
using UnitedPigeonAirlines.Data.Entities.PigeonAggregate;
using UnitedPigeonAirlines.Data.Repositories;

namespace UnitedPigeonAirlines.WebUI.Controllers
{
    public class PigeonController : Controller
    {
        private IPigeonRepository repository;
        public int pageSize = 4;
        
        
        public PigeonController(IPigeonRepository repo)
        {
            repository = repo;
        }
        
        public FileContentResult GetImage(int pigeonId)
        {
            Pigeon pigeon = repository.GetPigeon(pigeonId);
            
               

            if (pigeon != null)
            {
                return File(pigeon.ImageData, pigeon.ImageMimeType);
            }
            else
            {
                return null;
            }
        }
        public ViewResult List(string category, int page = 1)
        {
            PigeonListViewModel model = new PigeonListViewModel
            {
                Pigeons = repository.GetByCategory(category, page, pageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    TotalItems = repository.Count(category)
                },
                CurrentCategory = category
            };
            return View(model);
        }
        public PartialViewResult Menu(string category = null)
        {
            ViewBag.SelectedCategory = category;

            IEnumerable<string> categories = repository.GetAllPigeons()
                .Select(pigeon => pigeon.Category)
                .Distinct()
                .OrderBy(x => x);
            return PartialView(categories);
        }
    }
}

UnitedPigeonAirlines.WebUI/Views/Shared/PigeonSummary.cshtml
@model UnitedPigeonAirlines.Data.Entities.PigeonAggregate.Pigeon


<div class="well">
    @if (Model.ImageData != null)
    {
        <div class="pull-left" style="margin-right: 10px">
            <img class="img-thumbnail" width="150" height="150"
                 src="@Url.Action("GetImage", "Pigeon",
                new { Model.PigeonId })" />
        </div>
    }

    <h3>
        <strong>@Model.PigeonName</strong>
        <span class="pull-right label label-primary">@Model.BasicPrice.ToString("# UAH")</span>
    </h3>
    @using (Html.BeginForm("AddToCart", "Cart"))
    {
        <div class="pull-right">
            @Html.HiddenFor(x => x.PigeonId)
            @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
            <input type="submit" class="btn btn-success" value="Add to cart" />
        </div>
    }
    <span class="lead">@Model.Description</span>
</div>

UnitedPigeonAirlines.WebUI/Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.9.1.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <title></title>
</head>
<body>
    <div>
        @if (TempData["message"] != null)
        {
            <div class="alert alert-success">@TempData["message"]</div>
        }
        @RenderBody()
    </div>
</body>
</html>

UnitedPigeonAirlines.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div class="navbar navbar-inverse" role="navigation">
        <a class="navbar-brand" href="#">United Pigeon Airlines - new word in ecological transportation</a>
        @Html.Action("Summary", "Cart")
    </div>
    <div class="row panel">
        <div id="categories" class="col-xs-3">
            @Html.Action("Menu", "Nav")
        </div>
        <div class="col-xs-8">
            @RenderBody()
        </div>
    </div>
</body>
</html>