UnitedPigeonAirlines.WebUI/Controllers/AdminController.cs
using System.Web.Mvc;
using System.Linq;
using System.Web;
using UnitedPigeonAirlines.EF.Repositories;
using UnitedPigeonAirlines.Data.Entities.PigeonAggregate;
using UnitedPigeonAirlines.WebUI.Models;
using UnitedPigeonAirlines.Data.Repositories;

namespace UnitedPigeonAirlines.WebUI.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        IPigeonRepository repository;

        public AdminController(IPigeonRepository repo)
        {
            repository = repo;
        }

        public ViewResult Index()
        {
            return View(repository.GetAllPigeons());
        }
        public ViewResult Edit(int pigeonId)
        {



            Pigeon pigeon = repository.GetAllPigeons()
                .FirstOrDefault(g => g.PigeonId== pigeonId);
            PigeonViewModel pigeonDTO = new PigeonViewModel(pigeon);
            
            return View(pigeonDTO);
        }
        [HttpPost]
        public ActionResult Edit(PigeonViewModel pigeon, HttpPostedFileBase image = null)
        {
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    pigeon.ImageMimeType = image.ContentType;
                    pigeon.ImageData = new byte[image.ContentLength];
                    image.InputStream.Read(pigeon.ImageData, 0, image.ContentLength);
                }
                
                    repository.SavePigeon(pigeon.ToPigeon());
                
                TempData["message"] = string.Format("Changes in pigeon \"{0}\" info were saved", pigeon.PigeonName);
                return RedirectToAction("Index");
            }
            else
            {
                return View(pigeon);
            }
        }

        public ViewResult Create()
        {
            return View("Edit", new PigeonViewModel());
        }
        public ActionResult Delete(int pigeonId)
        {
            Pigeon deletedPigeon = repository.DeletePigeon(pigeonId);
            if (deletedPigeon != null)
            {
                TempData["message"] = string.Format("Pigeon \"{0}\" was deleted",
                    deletedPigeon.PigeonName);
            }
            return RedirectToAction("Index");
        }
    }
}

UnitedPigeonAirlines.WebUI/Controllers/PigeonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UnitedPigeonAirlines.EF.Repositories;
using UnitedPigeonAirlines.WebUI.Models;
using UnitedPigeonAirlines.Data.Entities.PigeonAggregate;
using UnitedPigeonAirlines.Data.Repositories;

namespace UnitedPigeonAirlines.WebUI.Controllers
{
    public class PigeonController : Controller
    {
        private IPigeonRepository repository;
        public int pageSize = 4;
        
        
        public PigeonController(IPigeonRepository repo)
        {
            repository = repo;
        }
        
        public FileContentResult GetImage(int pigeonId)
        {
            Pigeon pigeon = repository.GetPigeon(pigeonId);
            
               

            if (pigeon != null)
            {
                return File(pigeon.ImageData, pigeon.ImageMimeType);
            }
            else
            {
                return null;
            }
        }
        public ViewResult List(string category, int page = 1)
        {
            PigeonListViewModel model = new PigeonListViewModel
            {
                Pigeons = repository.GetByCategory(category, page, pageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    TotalItems = repository.Count(category)
                },
                CurrentCategory = category
            };
            return View(model);
        }
        public PartialViewResult Menu(string category = null)
        {
            ViewBag.SelectedCategory = category;

            IEnumerable<string> categories = repository.GetAllPigeons()
                .Select(pigeon => pigeon.Category)
                .Distinct()
                .OrderBy(x => x);
            return PartialView(categories);
        }
    }
}

UnitedPigeonAirlines.WebUI/Views/Admin/Edit.cshtml
@model UnitedPigeonAirlines.WebUI.Models.PigeonViewModel

@{
    ViewBag.Title = "Admin Panel: Editing";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="panel">
    <div class="panel-heading">
        <h3>Pigeon editing «@Model.PigeonName»</h3>
    </div>

    @using (Html.BeginForm("Edit", "Admin",
        FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div class="panel-body">
            @Html.HiddenFor(m => m.PigeonId)
            @foreach (var property in ViewData.ModelMetadata.Properties)
            {
                switch (property.PropertyName)
                {
                    case "PigeonId":
                    case "ImageData":
                    case "ImageMimeType":
                        break;
                    default:
            <div class="form-group">
                <label>@(property.DisplayName ?? property.PropertyName)</label>
                @if (property.PropertyName == "Description")
                {
                    @Html.TextArea(property.PropertyName, null,
                        new { @class = "form-control", rows = 5 })
                }
                else if (property.PropertyName == "Price")
                {
                    @Html.TextBox(property.PropertyName, null,
                        new
                             {
                                 @class = "form-control",
                                 Value = String.Format("{0:0.##}", Model.BasicPrice)
                             })
                }
                else
                {
                    @Html.TextBox(property.PropertyName, null,
                        new { @class = "form-control" })
                }
                @Html.ValidationMessage(property.PropertyName)
            </div>
                        break;
                }
            }
            <div class="form-group">
                <div style="position:relative;">
                    <label>Photo</label>
                    <a class='btn' href='javascript:;'>
                        Choose file...
                        <input type="file" name="Image" size="80"
                               style="position:absolute;z-index:2;top:0;
                                left:0;filter: alpha(opacity=0); opacity:0;
                                background-color:transparent;color:transparent;"
                               onchange='$("#upload-file-info").html($(this).val());'>
                    </a>
                    <span class='label label-info' id="upload-file-info"></span>
                </div>
                @if (Model.ImageData == null)
                {
                    <div class="form-control-static">No photo</div>
                }
                else
                {
                    <img class="img-thumbnail" width="300" height="300"
                         src="@Url.Action("GetImage", "Pigeon",
                        new { Model.PigeonId })" />
                }
            </div>
        </div>
        <div class="panel-footer">
            <input type="submit" value="Save" class="btn btn-primary" />
            @Html.ActionLink("Cancel changes and return to list", "Index", null, new
            {
                @class = "btn btn-default"
            })
        </div>
    }
</div>

UnitedPigeonAirlines.WebUI/Views/Admin/Index.cshtml
@model List<UnitedPigeonAirlines.Data.Entities.PigeonAggregate.Pigeon>

@{
    ViewBag.Title = "Admin panel: List of Pigeons";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="panel panel-default">
    <div class="panel-heading">
        <h3>List of Pigeons</h3>
    </div>
    <div class="panel-body">
        <table class="table table-striped table-condensed table-bordered">
            <tr>
                <th class="text-right">ID</th>
                <th>Name</th>
                <th class="text-right">Price</th>
                <th class="text-center">Actions</th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td class="text-right">@item.PigeonId</td>
                    <td>@Html.ActionLink(item.PigeonName, "Edit", new { item.PigeonId })</td>
                    <td class="text-right">@item.BasicPrice.ToString("# UAH")</td>
                    <td class="text-center">
                        @using (Html.BeginForm("Delete", "Admin"))
                        {
                            @Html.Hidden("PigeonId", item.PigeonId)
                            <input type="submit"
                                   class="btn btn-default btn-xs"
                                   value="Delete" />
                        }
                    </td>
                </tr>
            }
        </table>
    </div>
    <div class="panel-footer">
        @Html.ActionLink("Add Pigeon", "Create", null,
            new { @class = "btn btn-default" })
    </div>
</div>